# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9694ba3e5e97e5d9facae00f957b290ce78f385252fa13fe149be3ab2ff010923e9e9a7961a173e57ea8040b5f073c12bb14ab78238ca15a2fb5b8734cc5b2c

test:
  secret_key_base: ee45945d050ef5e364744e50a02f6078a56c184e89466860d03c06af3248f7fc090be7872da86e5db3f1152d1da54d4e2a60f952292b7207f308fbcac5474cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
